# Generated by Django 2.1.2 on 2018-10-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_auto_20181024_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added',
            name='item',
        ),
        migrations.RemoveField(
            model_name='added',
            name='user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Added',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
